### ISSUE TITLE
has something broken?

### ISSUE THREAD

**Issue by darren3** [snarfed/facebook-atom#13]
Hi, has something broken? I have not had any updates on my feed since Tuesday, I tried setting up a new feed url with a new cookie but same result.

**Comment by snarfed** [comment]
hey, thanks for the report, and sorry for the trouble! facebook-atom filters out a lot of posts that facebook shows in your news feed: when your friends like or comment or share on something, when your friends are mentioned, when they add new friends, etc. facebook-atom tries to only show actual posts that your friends post. looking at the logs for your feed, it looks like there haven't been any actual posts from your friends in the last couple days, so that's probably the reason.

**Comment by snarfed** [comment]
details in #9.
