### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by abliss** [snarfed/facebook-atom#24]
Following instructions (on Ubunutu 18.04), I get this error from pip:
```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting oauth_dropins
  Cloning https://github.com/snarfed/oauth-dropins.git (to revision master) to /tmp/pip-install-SOf_Dp/oauth-dropins
  Running command git clone -q https://github.com/snarfed/oauth-dropins.git /tmp/pip-install-SOf_Dp/oauth-dropins
  Running command git submodule update --init --recursive -q
Collecting granary
  Cloning https://github.com/snarfed/granary.git (to revision master) to /tmp/pip-install-SOf_Dp/granary
  Running command git clone -q https://github.com/snarfed/granary.git /tmp/pip-install-SOf_Dp/granary
  Running command git submodule update --init --recursive -q
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.9.3-py2-none-any.whl (115 kB)
     |████████████████████████████████| 115 kB 3.7 MB/s
Collecting google-cloud-logging~=1.14
  Downloading google_cloud_logging-1.15.1-py2.py3-none-any.whl (141 kB)
     |████████████████████████████████| 141 kB 9.6 MB/s
ERROR: Could not find a version that satisfies the requirement gunicorn~=20.0 (from -r requirements.txt (line 11)) (from versions: 0.1, 0.2, 0.2.1, 0.3, 0.3.1, 0.3.2, 0.4, 0.4.1, 0.4.2, 0.5, 0.5.1, 0.6, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.14.5, 0.14.6, 0.15.0, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 17.5, 18.0, 19.0.0, 19.1.0, 19.1.1, 19.2.0, 19.2.1, 19.3.0, 19.4.0, 19.4.1, 19.4.2, 19.4.3, 19.4.4, 19.4.5, 19.5.0, 19.6.0, 19.7.0, 19.7.1, 19.8.0, 19.8.1, 19.9.0, 19.10.0)
ERROR: No matching distribution found for gunicorn~=20.0 (from -r requirements.txt (line 11))
```

**Comment by abliss** [comment]
As a workaround I tried `virtualenv -p/usr/bin/python3 local` instead of `virtualenv local`. It seemed to work but later failed with a message about `ensurepip`.
So instead I installed python3.9 and python3.9-venv from the deadsnakes ppa and ran `python3.9 -m venv local`.
FYI the google appengine sdk does not recognize 'python39' as a valid runtime, so I followed the hack at https://stackoverflow.com/a/65695698/1239095 .

**Comment by snarfed** [comment]
Thanks for jumping in, and apologies for the setup trouble! The instructions are clearly out of date. `python3.9 -m venv local` is indeed the right/better way to set up a python 3 virtualenv, and the local App Engine stack is now `gcloud`-based instead of the old SDK, which is very obsolete.

[Here's an example of more up to date setup instructions.](https://github.com/snarfed/bridgy#development) I'll update this repo's soon.

[I'm also in the process of porting this to granary's Facebook scraping code](https://github.com/snarfed/facebook-atom/commit/f365f959b227038c692eeff67191c8160b454476), which should fix it. Just hasn't been a priority recently, real life and all. [Feel free to jump into the branch!](https://github.com/snarfed/facebook-atom/commit/f365f959b227038c692eeff67191c8160b454476)

**Comment by snarfed** [comment]
OK, granary port is done, this should be up and running again. It's still a work in progress, missing pictures and some other bits, but I'll keep working on it.
